### ISSUE TITLE
Can't resolve path when importing from js.

### ISSUE THREAD

**Issue by markhermano** [indooorsman/esbuild-plugin-path-alias#2]
I followed the usage guide:

```js
const vuePlugin = require("esbuild-plugin-vue3");
const { sassPlugin } = require("esbuild-sass-plugin");
const aliasPlugin = require('esbuild-plugin-path-alias');
const path = require('path');

require("esbuild").build({
  entryPoints: ["app/javascript/application.js"],
  bundle: true,
  minify: process.argv[2] === "--minify=true",
  watch: process.argv[2] === "--watch=true",
  outfile: "app/assets/builds/application.js",
  logLevel: "info",
  plugins: [vuePlugin(), sassPlugin(),
    aliasPlugin({
      "~": path.resolve(__dirname, "./app/javascript/components")
    })
  ],
}).catch(() => process.exit(1));
```
But I still get an error when importing from a `js` file. It works when importing from .vue files though.
Any thoughts?

![image](https://user-images.githubusercontent.com/16017297/178034359-4a358fa2-ede8-4d0c-b55b-a2dd29958d49.png)

**Comment by indooorsman** [comment]
try to move this plugin to top of `plugins`:

```
  plugins: [
    aliasPlugin({
      "~": path.resolve(__dirname, "./app/javascript/components")
    }),
    vuePlugin(), sassPlugin(),
  ],
```

**Comment by markhermano** [comment]
@indooorsman Thanks for the response. The plugin is actually working and I have made several aliases and it worked.

The issue I'm facing here is about dynamic importing which is not yet support by esbuild. We're just waiting for this PR to get merged. https://github.com/evanw/esbuild/pull/1273
